### ISSUE TITLE
Batch DRT analysis of data sets of a project in the same way in the GUI interface

### ISSUE THREAD

**Issue by zionLi3** [vyrjana/DearEIS#12]
I have a large amount of data. I need to conduct DRT analysis on the data sets of a project in batches in the GUI interface according to the same method, or I need to click again and again.

In your examples, Batch processing results shows how to batch process DRT analysis, but it uses all methods. My analysis speed is very slow. Can I select only one method (such as TR-RBF) for analysis？

Thank you very much indeed!

**Comment by zionLi3** [comment]
> I'm trying to finish up version 4.0.0 of both DearEIS and pyimpspec. That work will hopefully be ready soon but it does mean that I'm reluctant to add features as part of a new version 3.x.x release. However, I can see about adding support for batch analysis in the GUI for version 4.0.0.
> 
> Unfortunately, I'm not sure how soon version 4.0.0 will be released. I still have a few urgent tasks on the list of stuff to do before release. These tasks include both changes to the codebase and updating the documentation.
> 
> If this is an urgent matter and you are familiar with Python, then I would recommend using DearEIS' (or pyimpspec's) API to perform the batch analysis.
> 
> > In your examples, Batch processing results shows how to batch process DRT analysis, but it uses all methods. My analysis speed is very slow. Can I select only one method (such as TR-RBF) for analysis？
> 
> I'm not sure what you mean by "uses all methods". Which example are you referring to? Yes, you can choose which method to use. The `calculate_drt` functions found in the DearEIS and the pyimpspec APIs only use one method at a time. The following is a slightly modified version of what can be found in [this Jupyter notebook (input 21)](https://github.com/vyrjana/DearEIS/blob/main/examples/examples.ipynb):
> 
> ```python
> import deareis
> 
> project: deareis.Project = deareis.Project.from_file("some path")
> 
> data: deareis.DataSet
> for data in project.get_data_sets():
>     drt: DRTResult = deareis.calculate_drt(data, deareis.DRTSettings(
>         method=deareis.DRTMethod.TR_RBF,
>         rbf_type=deareis.RBFType.GAUSSIAN,
>         rbf_shape=deareis.RBFShape.FWHM,
>         shape_coeff=0.5,
>         derivative_order=1,
>         num_samples=10000,
>         num_attempts=5,
>         maximum_symmetry=0.5,
>         mode=deareis.DRTMode.COMPLEX,
>         lambda_value=-1.0,
>         inductance=False,
>         credible_intervals=False,
>         # The rest are not relevant for this method,
>         # but these would be always be included when using the GUI
>         circuit=None,
>         W=0.15,
>         num_per_decade=50,
>     ))
>     project.add_drt(data, drt)
> 
> # You can also provide the `save` method with a `path`
> # argument to save the modified project to another file.
> project.save()
> ```
> 
> Some methods are slower than others. For example, BHT and TR-RBF are slower than TR-NNLS. The settings can also have a significant impact on how long it takes. For example, for the TR-RBF method the following parameters can greatly affect how long it takes:
> 
> * `credible_intervals=True` adds another part to the analysis, which is then affected by the `num_samples` parameter
> * not providing a regularization parameter (i.e. not providing a positive value for the `lambda_value` parameter) will also make the analysis take longer since multiple values will be tested in an attempt to find a suitable value

Thank you very much! I have realized the analysis I want through DearEIS' API. This is really a very useful program.

**Comment by vyrjana** [comment]
If we use your example, then I think the steps would be as follows:

- [Mask the mid- and high-frequency data points in the `Data sets` tab so that only the low-frequency portion is visible.](https://vyrjana.github.io/DearEIS/guide_data.html#masking-data-points)
- Fit a suitable circuit to this low-frequency portion. It looks like they used a resistance in series with a Warburg impedance and a capacitor in the example you provided.
- [Copy the **extended** circuit description code (`CDC - extended`) for the fitted circuit.](https://vyrjana.github.io/DearEIS/guide_fitting.html#copying-results-to-the-clipboard)
- [Go to the `Data sets` tab, click `Process`, and open up the `Subtract impedance` window.](https://vyrjana.github.io/DearEIS/guide_data.html#subtraction)
- Choose the `Circuit` option, paste the CDC that you copied into the input, remove the series resistance (either by deleting the `R{R=...}` part of the CDC or via the graphical editor that you can open by clicking the `Edit` button), and click `Accept`.
