### ISSUE TITLE
100% CPU usage problem

### ISSUE THREAD

**Issue by GregAlex7** [vyrjana/DearEIS#15]
Hello, I'm not used to GitHub so I hope that this is the right space to ask for this information.
I'm trying to use DearEIS in his GUI version, and I'm having some trubles, each time that i run a process the CPU usage go up to 100% and if the process is very long (ex. Hilbert transform in DRT) i can't use my PC at all.
Is there any way to limit the program usage of my CPU when i run the program?
I've installed it on a virtual space, I'm using VSCode.

I've tried to manage this issue by using the infromations reported in the API, to do so I've wrote a little .py script:

import deareis

# Check the starting number of procs used
default_num_procs = deareis.get_default_num_procs()
print(default_num_procs)  # This will print the default number of processes

# Set the desired number of processes
num_procs = 4

deareis.set_default_num_procs(num_procs)

# Check how many procs are used
default_num_procs = deareis.get_default_num_procs()
print(default_num_procs)

But actually each time that I run "deareis" in his GUI version from the terminal it starts again from the maximum amount of procs.
Should I add in this script the GUI version run? And if so, how? I searched for the .exe file but i didn't found it.

Thanks in advance for any kind of help, please try to be explicit with everything because I'm a complete noob.

Bye

EDIT: I've found out that I can limit the procs from the settings, but still the problem specifically start each time that i try to run the Hilbert Transformation, here the CPU stay stucked to 100% even if I close the windows. I need to shut down all the python processes from the Task Manager

**Comment by GregAlex7** [comment]
The problem specifically start each time that i try to run the Hilbert Transformation, here the CPU stay stucked to 100% even if I close the windows. I need to shut down all the python processes from the Task Manager.

**Comment by GregAlex7** [comment]
I'm even struggling with the m(RQ)fit method, since I can't put anything in the "circuit", probably I'm doing something wrong, but I don't get what.

**Comment by vyrjana** [comment]
## High CPU utilization

I suspect that the NumPy package that you have installed is making use of a multithreaded BLAS library such as OpenBLAS. You can check which library NumPy is using by running the following command in the terminal (you may need to replace `python3` with whatever is applicable for your operating system):

```bash
python3 -c "from numpy import show_config; show_config()"
```

If you see instances of `openblas` or `openblas64` in the output, then that might explain the high CPU utilization despite telling DearEIS to use fewer processes (note *processes* not *threads*).

DearEIS can make use of multiple processes to improve performance by performing operations in parallel, but this can cause very high CPU utilization when combined with a multithreaded BLAS library. However, DearEIS should – unless it is told otherwise by the user – automatically reduce the number of processes that it uses (e.g., down to a single process) when it detects that NumPy is using OpenBLAS in a multithreaded fashion. If you want to reduce the CPU utilization further, then you'll need to also set the relevant environment variable that tells the relevant BLAS library to use fewer threads. For example, on Linux you would run the following command in the terminal (before running DearEIS from that same terminal instance) to tell OpenBLAS to use a single thread:

```bash
export OPENBLAS_NUM_THREADS=1
```

So if you want minimal CPU utilization, then you'll need to tell both the BLAS library to use fewer threads AND DearEIS to use fewer processes. The former requires setting an environment variable and the latter can be done via the settings menu.


## Using the m(RQ)fit method

- Go to the `Fitting` tab.
- Select the data set you want to analyze.
- Construct a suitable equivalent circuit that fulfills the requirements set by the m(RQ)fit method.
- Fit the equivalent circuit to the chosen data set.
- Go to the `DRT analysis` tab (the correct data set should already be selected at this point).
- Select the `m(RQ)fit` method.
- Select the fitted circuit from the `Circuit` drop-down box, which should now include the circuit that you fitted in the `Fitting` tab.
- Click `Perform`.

If you want to analyze another data set, then you'll need to (construct and) fit a circuit to that data set before performing the analysis.

**Comment by GregAlex7** [comment]
Thank you!! Sorry for the delay in my answer, but I wanted to be sure and test some stuff.
I'm really enjoying DearEIS!

As you said I checked and I have OpenBLAS active, now I'll try to figure out how to properly manage it.

I've even been able to properly use m(RQ)fit!

I wanted to ask another thing, I would like to run a fit and then slightly modify the parameters (or fix some of them) and then run again the fitting, but each time I must copy the value by hand, is there a way to directly load the parameters in the equivalent circuit?
I tried by pressing on "Apply settings" and then I checked on both the "Edit" and the "Adjust Parameters" section but the values are not updated. Am I missing something?

**Comment by vyrjana** [comment]
The `Apply settings` button adjusts the settings back to what they were in order to obtain the currently chosen fit result. Let's say that you fitted model A to spectrum 1, altered the model (now model B), fitted model B to spectra 1 and 2, and then decided that you wanted to fit model A to spectrum 2 as well. You would then select spectrum 1, select the result for model A, click `Apply settings`, and now you would be able to fit model A to spectrum 2 without having to manually recreate model A (and any other settings you may have had chosen).

Someone else contacted me a while back and also requested the ability to quickly copy the fitted parameters and use them as the initial values for the next fit. I have that implemented in the update I'm working on, but I cannot provide an ETA for when that update will be available since there are a lot of other things to also finish up. At the moment, you can achieve the same effect by selecting the `CDC - extended` option from the `Output` drop-down menu, clicking `Copy`, and then pasting the copied string of text into the `Circuit` input field (or the `CDC input` input field in the `Circuit editor` window), and pressing `Enter`.
