### ISSUE TITLE
build.sh is not executable

### ISSUE THREAD

**Issue by Aslan-Kosakian** [vyrjana/DearEIS#6]
**Desktop (please complete the following information):**
- _DearEIS_ version 3.1.3
- Python version 3.8.10
- OS: Ubuntu 20.04

**Describe the bug**
The build.sh script that comes with the software is not executable. If I run “chmod +x build.sh”, then the script complains that it’s been modified and does not run (“Detected uncommitted changes and/or untracked files!”).

**To Reproduce**
1. Go to 'DearEIS/'
2. Run 'build.sh'.

**Comment by vyrjana** [comment]
The `build.sh` script can also be executed without making the script executable by passing the file's path to `bash`. The script is also something that very few people would need to run since it is used primarily to build the source and wheel distributions that are uploaded to PyPI.

The script complains about uncommitted changes and/or untracked files specifically as a measure to prevent accidental inclusion of uncommitted changes or untracked files in the source and wheel distributions.

I consider the script to be functioning as intended.

**Comment by vyrjana** [comment]
I have updated `build.sh` to use `python3` instead of `python` in [this commit](https://github.com/vyrjana/DearEIS/commit/469d528da4127db56f1612c430df07caf8a02adf). I have also updated `setup.py` to include optional dependencies for development and added a bit of information about this to the "Contributing" section of the readme (see [this commit](https://github.com/vyrjana/DearEIS/commit/b176be1f947d0812fafdb6c3de62e110590c5af0)).

**Comment by Aslan-Kosakian** [comment]
Thank you for the changes. The issue can be closed now.
