### ISSUE TITLE
Closing confirmation

### ISSUE THREAD

**Issue by Aslan-Kosakian** [vyrjana/DearEIS#9]
Please implement a dialogue window asking the user to confirm closing the application. The opened project is automatically saved and opened the next time the GUI is executed; however, this feature would save the users’ time if they clicked the close button by accident.

**Comment by vyrjana** [comment]
This does not seem to be possible at the moment, which is why I implemented automatic saving and recovery of projects with unsaved changes. The GUI framework, Dear PyGui, does have a `set_exit_callback` function but there does not seem to be a way to intercept/cancel the shutdown process like one can with some other frameworks. There is an [open issue](https://github.com/hoffstadt/DearPyGui/issues/227) requesting this feature but that was opened two years ago and as far as I can tell the feature has not yet been implemented.

**Comment by Aslan-Kosakian** [comment]
Thank you. Since this is a limitation of Dear PyGui, I'm closing this issue.

**Comment by Aslan-Kosakian** [comment]
Thank you. Since this is a limitation of Dear PyGui, I'm closing this issue.
